### ISSUE TITLE
Worked once, then stopped working

### ISSUE THREAD

**Issue by vklages** [FrancoisMentec/PoE-Trade-Extension#4]
I searched for an item, it worked, I sorted the listings and since then the extension stopped working.
Console says:
```
VM375:93 exception thrown: TypeError: Cannot read property '0' of undefined,TypeError: Cannot read property '0' of undefined
    at triggerInput (chrome-extension://opoildjhholnkfphcbmcjgcehbkjmoam/js/pob-injected.js:150:22)
    at Object.draw.EndFrame (chrome-extension://opoildjhholnkfphcbmcjgcehbkjmoam/js/pob-injected.js:85:7)
    at _js_EndFrame (https://pob.party/pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:7448:7)
    at wasm-function[269]:0x26829
    at wasm-function[345]:0x38591
    at Object.Module.dynCall_v (https://pob.party/pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:8220:29)
    at browserIterationFunc (https://pob.party/pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:7200:23)
    at Object.runIter (https://pob.party/pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:6566:5)
    at Browser_mainLoop_runner (https://pob.party/pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:7238:20)
```
and
```
pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:6572 Uncaught TypeError: Cannot read property '0' of undefined
    at triggerInput (pob-injected.js:150)
    at Object.draw.EndFrame (pob-injected.js:85)
    at _js_EndFrame (pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:7448)
    at pob.party/wasm-function[269]:0x26829
    at pob.party/wasm-function[345]:0x38591
    at Object.Module.dynCall_v (pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:8220)
    at browserIterationFunc (pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:7200)
    at Object.runIter (pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:6566)
    at Browser_mainLoop_runner (pob-aa6a96ce0a05603756487e0ad38b370c0931167e.js:7238)
```

**Comment by FrancoisMentec** [comment]
So the error is caused by the size of your window, it's too small so some elements of PoB aren't rendered and can't found by the extension. There is a line about that in the readme.
1. I made a custom error message so the cause of the error should be easier to find for the user.
2. I manually set the size of the iframe and it appears to be rendering elements that are out the window. So the error should be gone, you just have to install the latest version (the one on the firefox webstore isn't updated yet).  

If you still encounter the error don't hesitate to re-open the issue.
