### ISSUE TITLE
Worked a few times and then ran into the "Failed to find the coordinates of "create"

### ISSUE THREAD

**Issue by Arradinn** [FrancoisMentec/PoE-Trade-Extension#8]
First time using it and it worked for several searches and then I started to get the error saying "Failed to get the coordinates of "Create". Try to maximise your window then refresh the page." The page was maximized already so I shrunk it and remaximized it which didn't fix it. Tried restarted chrome and my computer and uninstalling the trade extension and reinstalling it which didn't work either.

Any help would be greatly appreciated because this is a great addon.

Here is the console
Loading main script...
(index):93 Loading passive tree data for version '3.14'...
(index):93 Loading passive tree assets...
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6098 PathOfBuilding/TreeData/JewelSocketActiveAltPurple.png - not found
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6098 PathOfBuilding/TreeData/JewelSocketActiveAltRed.png - not found
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6098 PathOfBuilding/TreeData/JewelSocketActiveAltBlue.png - not found
(index):93 Processing tree...
(index):93 Loading item databases...
draw.js:106 Recreating palette with 0 colors
draw.js:106 Recreating palette with 1 colors
draw.js:106 Recreating palette with 2 colors
draw.js:106 Recreating palette with 3 colors
draw.js:106 Recreating palette with 4 colors
draw.js:106 Recreating palette with 5 colors
draw.js:106 Recreating palette with 6 colors
draw.js:106 Recreating palette with 7 colors
draw.js:106 Recreating palette with 8 colors
draw.js:106 Recreating palette with 9 colors
draw.js:106 Recreating palette with 10 colors
draw.js:106 Recreating palette with 11 colors
draw.js:106 Recreating palette with 12 colors
draw.js:106 Recreating palette with 13 colors
draw.js:106 Recreating palette with 14 colors
draw.js:106 Recreating palette with 15 colors
draw.js:106 Recreating palette with 16 colors
draw.js:106 Recreating palette with 17 colors
draw.js:106 Recreating palette with 18 colors
draw.js:106 Recreating palette with 19 colors
draw.js:106 Recreating palette with 20 colors
draw.js:106 Recreating palette with 21 colors
draw.js:106 Recreating palette with 22 colors
draw.js:106 Recreating palette with 23 colors
draw.js:106 Recreating palette with 24 colors
draw.js:106 Recreating palette with 25 colors
draw.js:106 Recreating palette with 26 colors
draw.js:106 Recreating palette with 27 colors
draw.js:106 Recreating palette with 28 colors
draw.js:106 Recreating palette with 29 colors
(index):93 exception thrown: TypeError: Cannot read property 'apply' of undefined,TypeError: Cannot read property 'apply' of undefined
    at triggerInput (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:174:25)
    at Object.draw.EndFrame (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:85:7)
    at _js_EndFrame (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027:10)
    at https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981:9)
    at Object.runIter (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037:11)
    at Browser_mainLoop_runner (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727:26)
printErr @ (index):93
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4988 Uncaught TypeError: Cannot read property 'apply' of undefined
    at triggerInput (pob-injected.js:174)
    at Object.draw.EndFrame (pob-injected.js:85)
    at _js_EndFrame (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027)
    at pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981)
    at Object.runIter (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037)
    at Browser_mainLoop_runner (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727)
pob-injected.js:159 TypeError: Cannot read property '0' of undefined
    at triggerInput (pob-injected.js:155)
    at Object.draw.EndFrame (pob-injected.js:85)
    at _js_EndFrame (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027)
    at pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981)
    at Object.runIter (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037)
    at Browser_mainLoop_runner (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727)
triggerInput @ pob-injected.js:159
trade.js:202 Failed to get the coordinates of "Create". Try to maximise your window then refresh the page.
message @ trade.js:202
(index):93 exception thrown: TypeError: Cannot read property 'apply' of undefined,TypeError: Cannot read property 'apply' of undefined
    at triggerInput (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:174:25)
    at Object.draw.EndFrame (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:85:7)
    at _js_EndFrame (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027:10)
    at https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981:9)
    at Object.runIter (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037:11)
    at Browser_mainLoop_runner (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727:26)
printErr @ (index):93
(index):93 [post-exception status] Exception thrown, see JavaScript console
printErr @ (index):93
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4988 Uncaught TypeError: Cannot read property 'apply' of undefined
    at triggerInput (pob-injected.js:174)
    at Object.draw.EndFrame (pob-injected.js:85)
    at _js_EndFrame (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027)
    at pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981)
    at Object.runIter (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037)
    at Browser_mainLoop_runner (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727)
draw.js:106 Recreating palette with 30 colors
draw.js:106 Recreating palette with 31 colors
draw.js:106 Recreating palette with 32 colors
(index):93 exception thrown: TypeError: Cannot read property 'apply' of undefined,TypeError: Cannot read property 'apply' of undefined
    at triggerInput (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:174:25)
    at Object.draw.EndFrame (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:85:7)
    at _js_EndFrame (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027:10)
    at https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981:9)
    at Object.runIter (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037:11)
    at Browser_mainLoop_runner (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727:26)
printErr @ (index):93
(index):93 [post-exception status] Exception thrown, see JavaScript console
printErr @ (index):93
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4988 Uncaught TypeError: Cannot read property 'apply' of undefined
    at triggerInput (pob-injected.js:174)
    at Object.draw.EndFrame (pob-injected.js:85)
    at _js_EndFrame (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027)
    at pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981)
    at Object.runIter (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037)
    at Browser_mainLoop_runner (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727)
(index):93 exception thrown: TypeError: Cannot read property 'apply' of undefined,TypeError: Cannot read property 'apply' of undefined
    at triggerInput (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:174:25)
    at Object.draw.EndFrame (chrome-extension://ckfnddafphjahhiadjogilncdegmbpkm/js/pob-injected.js:85:7)
    at _js_EndFrame (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027:10)
    at https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981:9)
    at Object.runIter (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037:11)
    at Browser_mainLoop_runner (https://pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727:26)
printErr @ (index):93
(index):93 [post-exception status] Exception thrown, see JavaScript console
printErr @ (index):93
pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4988 Uncaught TypeError: Cannot read property 'apply' of undefined
    at triggerInput (pob-injected.js:174)
    at Object.draw.EndFrame (pob-injected.js:85)
    at _js_EndFrame (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6027)
    at pob.party/pob-9ce444030e2a748982ea57f64224fbe5371bb041.wasm:wasm-function[175]:0x10b45
    at callUserCallback (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:4981)
    at Object.runIter (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5037)
    at Browser_mainLoop_runner (pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:5727)

**Comment by Arradinn** [comment]
The issue might have started after I clicked the "Show POB" button, which seems to kinda bug out on my screen. If I hit show POB before it errors out it'll bring up the POB but if the error has happened the screen goes black with a large scroll bar like the resolution changed to something very different.

**Comment by Barragek0** [comment]
This started happening after pob updated to version 2.3.0 / pob.party updated to master/9ce4440

It doesn't seem to have anything to do with show pob button, I haven't clicked that.

Here's the console for firefox extension:

Loading main script... pob.party:93:354
Loading passive tree data for version '3.14'... pob.party:93:354
Loading passive tree assets... pob.party:93:354
PathOfBuilding/TreeData/JewelSocketActiveAltPurple.png - not found pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6098:14
PathOfBuilding/TreeData/JewelSocketActiveAltRed.png - not found pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6098:14
PathOfBuilding/TreeData/JewelSocketActiveAltBlue.png - not found pob-9ce444030e2a748982ea57f64224fbe5371bb041.js:6098:14
Processing tree... pob.party:93:354
Loading item databases... pob.party:93:354
Recreating palette with 0 colors draw.js:106:10
Recreating palette with 1 colors draw.js:106:10
Recreating palette with 2 colors draw.js:106:10
Recreating palette with 3 colors draw.js:106:10
Recreating palette with 4 colors draw.js:106:10
Recreating palette with 5 colors draw.js:106:10
Recreating palette with 6 colors draw.js:106:10
Recreating palette with 7 colors draw.js:106:10
Recreating palette with 8 colors draw.js:106:10
Recreating palette with 9 colors draw.js:106:10
Recreating palette with 10 colors draw.js:106:10
Recreating palette with 11 colors draw.js:106:10
Recreating palette with 12 colors draw.js:106:10
Recreating palette with 13 colors draw.js:106:10
Recreating palette with 14 colors draw.js:106:10
Recreating palette with 15 colors draw.js:106:10
Recreating palette with 16 colors draw.js:106:10
Recreating palette with 17 colors draw.js:106:10
Recreating palette with 18 colors draw.js:106:10
Recreating palette with 19 colors draw.js:106:10
Recreating palette with 20 colors draw.js:106:10
Recreating palette with 21 colors draw.js:106:10
Recreating palette with 22 colors draw.js:106:10
Recreating palette with 23 colors draw.js:106:10
Error: Promised response from onMessage listener went out of scope ExtensionMessagingService.js:89:34
Error: Promised response from onMessage listener went out of scope chrome.js:138:30
Error: Promised response from onMessage listener went out of scope common.js:4:491
Error: Promised response from onMessage listener went out of scope ExtensionMessagingService.js:89:34
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://13e31bed-bca9-4f87-a640-8a43d2eb7a7e/userscripts/poe-trade-official-site-enhancer.user.js?id=4bc63c47-bd55-43ab-a6c6-b8e497d39dd5
Source Map URL: bootstrap.min.js.map

Error: Promised response from onMessage listener went out of scope 3 common.js:4:491

**Comment by FrancoisMentec** [comment]
I merged @Barragek0 fix and published the new version (4.4) on the chrome and firefox webstore.
